import { Sistema, StatusSistema, TipoSistema, Integracao } from './types';

export const MOCK_SISTEMAS: Sistema[] = [
  {
    id: '1',
    sigla: 'CNC-ERP',
    nome: 'CNC Core ERP',
    descricao: 'Sistema central de gestão de recursos da empresa, controlando financeiro, contábil e fiscal.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.ERP,
    areaNegocio: 'Financeiro',
    donoNegocio: 'Carlos Silva',
    liderTecnico: 'Mariana Souza',
    fornecedor: 'SAP',
    tecnologias: ['ABAP', 'Java', 'Oracle'],
    linkProducao: 'https://erp.cnc.corp',
    dataImplantacao: '2015-06-10',
    criticidade: 'Crítica'
  },
  {
    id: '2',
    sigla: 'CNC-CRM',
    nome: 'Customer Relationship Manager',
    descricao: 'Gestão de relacionamento com clientes e funil de vendas.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Comercial',
    donoNegocio: 'Fernanda Lima',
    liderTecnico: 'Roberto Dias',
    fornecedor: 'Salesforce',
    tecnologias: ['Apex', 'Lightning Web Components'],
    linkProducao: 'https://crm.cnc.corp',
    dataImplantacao: '2019-03-20',
    criticidade: 'Alta'
  },
  {
    id: '3',
    sigla: 'CNC-LOG',
    nome: 'Logística Avançada',
    descricao: 'Controle de frota e roteirização de entregas.',
    status: StatusSistema.SUBSTITUICAO,
    tipo: TipoSistema.DESKTOP,
    areaNegocio: 'Logística',
    donoNegocio: 'Pedro Santos',
    liderTecnico: 'Lucas Pereira',
    fornecedor: 'Interno',
    tecnologias: ['Delphi', 'SQL Server'],
    dataImplantacao: '2008-01-15',
    criticidade: 'Média'
  },
  {
    id: '4',
    sigla: 'CNC-RH',
    nome: 'Portal do Colaborador',
    descricao: 'Autoatendimento de RH, holerites e benefícios.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Recursos Humanos',
    donoNegocio: 'Ana Beatriz',
    liderTecnico: 'Juliana Costa',
    fornecedor: 'Interno',
    tecnologias: ['React', 'Node.js', 'PostgreSQL'],
    linkProducao: 'https://rh.cnc.corp',
    dataImplantacao: '2022-11-05',
    criticidade: 'Média'
  },
  {
    id: '5',
    sigla: 'CNC-BI',
    nome: 'Business Intelligence Lake',
    descricao: 'Centralizador de dados analíticos para tomada de decisão.',
    status: StatusSistema.IMPLANTACAO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Estratégia',
    donoNegocio: 'Diretoria Executiva',
    liderTecnico: 'Marcos Vinicius',
    fornecedor: 'Microsoft',
    tecnologias: ['PowerBI', 'Azure Synapse'],
    dataImplantacao: '2024-01-01',
    criticidade: 'Alta'
  },
  {
    id: '6',
    sigla: 'LEG-FIN',
    nome: 'Financeiro Legado',
    descricao: 'Antigo sistema de contas a pagar, mantido apenas para consulta.',
    status: StatusSistema.DESCONTINUADO,
    tipo: TipoSistema.DESKTOP,
    areaNegocio: 'Financeiro',
    donoNegocio: 'Carlos Silva',
    liderTecnico: 'Mariana Souza',
    fornecedor: 'Interno',
    tecnologias: ['VB6', 'Access'],
    dataImplantacao: '2000-05-10',
    criticidade: 'Baixa'
  },
  // Novos sistemas baseados no fluxo de integrações
  {
    id: 'sys_argo',
    sigla: 'Argo it',
    nome: 'Argo It (gestão de viagens)',
    descricao: 'Sistema de gestão de viagens corporativas e despesas.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Administrativo',
    donoNegocio: 'Gestão de Viagens',
    liderTecnico: 'Equipe Externa',
    fornecedor: 'Argo Solutions',
    tecnologias: ['SaaS'],
    criticidade: 'Média'
  },
  {
    id: 'sys_rm',
    sigla: 'ERP - RM',
    nome: 'ERP - Sistema de Gestão (Linha RM)',
    descricao: 'Sistema ERP Backoffice Totvs Linha RM.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.ERP,
    areaNegocio: 'Financeiro',
    donoNegocio: 'CFO',
    liderTecnico: 'Coordenação ERP',
    fornecedor: 'Totvs',
    tecnologias: ['.NET', 'SQL Server'],
    criticidade: 'Crítica'
  },
  {
    id: 'sys_reserve',
    sigla: 'Reserve',
    nome: 'Sistema self check-in book (viagens e despesas corporativas)',
    descricao: 'Ferramenta de self-booking para viagens corporativas.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Administrativo',
    donoNegocio: 'Gestão de Viagens',
    liderTecnico: 'Equipe Externa',
    fornecedor: 'Reserve',
    tecnologias: ['SaaS'],
    criticidade: 'Média'
  },
  {
    id: 'sys_banca',
    sigla: 'Banca Digital',
    nome: 'Banca Digital (distribuição digital de revistas)',
    descricao: 'Plataforma de distribuição de revistas e periódicos digitais.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Editorial',
    donoNegocio: 'Diretoria de Conteúdo',
    liderTecnico: 'Tech Lead Digital',
    fornecedor: 'Interno',
    tecnologias: ['Node.js', 'React'],
    criticidade: 'Alta'
  },
  {
    id: 'sys_bdcs',
    sigla: 'BDCS',
    nome: 'Banco de Dados de Contribuições Sindicais',
    descricao: 'Base de dados consolidada para contribuições sindicais.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.API,
    areaNegocio: 'Sindical',
    donoNegocio: 'Gerência Sindical',
    liderTecnico: 'DBA Team',
    fornecedor: 'Interno',
    tecnologias: ['SQL Server', 'PL/SQL'],
    criticidade: 'Média'
  },
  {
    id: 'sys_cadu',
    sigla: 'Cadu',
    nome: 'Cadastro Único (informações de entidades sindicais)',
    descricao: 'Sistema de cadastro único para entidades sindicais.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Sindical',
    donoNegocio: 'Gerência de Cadastro',
    liderTecnico: 'Dev Team Alpha',
    fornecedor: 'Interno',
    tecnologias: ['Java', 'Spring Boot'],
    criticidade: 'Alta'
  },
  {
    id: 'sys_gds',
    sigla: 'GDS',
    nome: 'Gestão de Dados Sindicais',
    descricao: 'Sistema para gestão e análise de dados sindicais.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Sindical',
    donoNegocio: 'Gerência Sindical',
    liderTecnico: 'Dev Team Beta',
    fornecedor: 'Interno',
    tecnologias: ['Python', 'Django'],
    criticidade: 'Média'
  },
  {
    id: 'sys_wp',
    sigla: 'CMS - WordPress',
    nome: 'WordPress – gerenciador de conteúdo do portal',
    descricao: 'CMS utilizado para gestão de conteúdo do portal institucional.',
    status: StatusSistema.EM_USO,
    tipo: TipoSistema.WEB,
    areaNegocio: 'Comunicação',
    donoNegocio: 'Editoria Chefe',
    liderTecnico: 'Agência Partner',
    fornecedor: 'WordPress',
    tecnologias: ['PHP', 'MySQL'],
    criticidade: 'Média'
  }
];

export const MOCK_INTEGRACOES: Integracao[] = [
  { 
    id: '1', 
    sistemaOrigemId: 'sys_argo', 
    sistemaDestinoId: 'sys_rm', 
    tipo: 'API REST', 
    descricao: 'Solicitações aprovadas / reservas de viagem' 
  },
  { 
    id: '2', 
    sistemaOrigemId: 'sys_reserve', 
    sistemaDestinoId: 'sys_rm', 
    tipo: 'Arquivo', 
    descricao: 'Lançamentos de despesas de viagem' 
  },
  { 
    id: '3', 
    sistemaOrigemId: 'sys_banca', 
    sistemaDestinoId: 'sys_bdcs', 
    tipo: 'Arquivo', 
    descricao: 'Movimento de contribuições por publicação / edição' 
  },
  { 
    id: '4', 
    sistemaOrigemId: 'sys_cadu', 
    sistemaDestinoId: 'sys_gds', 
    tipo: 'API REST', 
    descricao: 'Dados de cadastro de sindicatos e entidades' 
  },
  { 
    id: '5', 
    sistemaOrigemId: 'sys_wp', 
    sistemaDestinoId: 'sys_banca', 
    tipo: 'API / Feed', 
    descricao: 'Matérias e conteúdos editoriais' 
  },
];